$(document).ready(function(){
    $(".ph-hs-btn").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","block");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-fe-btn").click(function(){
        $(".ph-fd-sw").css("display","block");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-sv-btn").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","block");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-fd-box").click(function(){
        $(".ph-fd-sw").css("display","block");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-fd").click(function(){
        $(".ph-fd-sw").css("display","block");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-st-box").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","block");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-st").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","block");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-dr").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","block");
    });
    $(".ph-sd-oh").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","block");
    });
    $(".ph-oh-safe").click(function(){
        $(".ph-qa-box").css("display","block");
        $(".ph-qa-bgc").css("display","block");
    });
    $(".qa-exit").click(function(){
        $(".ph-qa-box").css("display","none");
        $(".ph-qa-bgc").css("display","none");
        $(".ph-qa-topic").css("display","block");
    });
    $(".qa-right").click(function(){
        $(".ph-qa-right").css("display","flex");
        $(".ph-qa-wrong").css("display","none");
        $(".ph-qa-topic").css("display","none");
    });
    $(".qa-wrong").click(function(){
        $(".ph-qa-wrong").css("display","flex");
        $(".ph-qa-right").css("display","none");
        $(".ph-qa-topic").css("display","none");
    });


});