$(document).ready(function(){
    $(".ph-hs-btn").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","block");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-fe-btn").click(function(){
        $(".ph-fd-sw").css("display","block");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-sv-btn").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","block");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-fd-box").click(function(){
        $(".ph-fd-sw").css("display","block");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-fd").click(function(){
        $(".ph-fd-sw").css("display","block");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-st-box").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","block");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-st").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","block");
        $(".ph-oh-sw").css("display","none");
    });
    $(".ph-dr").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","block");
    });
    $(".ph-sd-oh").click(function(){
        $(".ph-fd-sw").css("display","none");
        $(".ph-hs-sw").css("display","none");
        $(".ph-pu-sw").css("display","none");
        $(".ph-oh-sw").css("display","block");
    });


});